### ISSUE TITLE
How to change data with getMeetings function

### ISSUE THREAD

**Issue by jervalles** [iNeoO/vue-meeting-selector#13]
After read this issue: https://github.com/iNeoO/vue-meeting-selector/issues/8
the codepen link doesn't work and it would maybe help me i guess.

The component works great but I don't know how to edit the getMeetings(date) function.

Actually I just receive every availabilities of a collaborator by props. But I don't know how to split the different available dates with that function. (create slots and return them)

Actually my function has this, but It just return the entire data. In this case, when I click next page, I just have the same datas: 
`getMeetings(date) {
   console.log(date)
   return this.available
},`
    
Here my code https://gist.github.com/jervalles/38fd703a2634d3cd8489585e7bce89b2
I've also paster the test Data (availability of a collaborator)

**Comment by iNeoO** [comment]
Hi, a working codpen, https://codesandbox.io/s/vue-meeting-selector-ex-l0s5p . If you still have trouble just ask

**Comment by jervalles** [comment]
Hi @iNeoO, thanks for your fast answer.

This codepend doesn't have the nextDate() and previousDate() function filed. And that's is what I need.
Because the DATA will just give every available day of a Collaborator and i need to have multiples pages.

I just didn't understand how I can write those nextDate() and previousDate() functions.
In my code, it's getMeetings() that is empty.

Thanks

**Comment by iNeoO** [comment]
you want only slot for :
- monday, 8h00, 11h00
- wenesday, 10h00, 13h00
- thursday, 10h00, 13h00
every week ?
how may days do you want to display in the selector ? (5 ? you can display 3)

**Comment by jervalles** [comment]
My data.json will change of course (it's just a sample data inside), I'm actually working on this feature before the backend team. In final, collaborators will add their disponibilities and it will update the data.json (of course it will not be a json, but async function from API).

So I will have alot more slots sets by collaborators.

What I need, is to handle this getMeetings() to get the data depending of the week we are looking on.

merci!

**Comment by iNeoO** [comment]
If you use an api, should be like this api/get/schedules?from=2021-02-08&to=2021-02-14 to get your init call

to get next you should do something like that
```javascript
format(value) {
  if (!value) {
    return '';
  }
  const date = new Date(value);
  const year = date.getFullYear();
  const month = (`${date.getMonth() + 1}`).padStart(2, 0);
  const day = (`${date.getDate()}`).padStart(2, 0);
  return `${year}-${month}-${day}`;
};
async nextDate() {
      this.loading = true;
      const from = new Date(this.date);
      from.setDate(date.getDate() + 7);
      const to = new Date(this.date);
      to.setDate(date.getDate() + 13);
      this.meetingsDays = await axios.get(`api/get/schedules?from=${this.format(from)}&to=${this.format(to)}`);
      this.date = from;
      this.loading = false;
},
async previousDate() {
      this.loading = true;
      const from = new Date(this.date);
      from.setDate(date.getDate() -7);
      const to = new Date(this.date);
      to.setDate(date.getDate() -1);
      this.meetingsDays = await axios.get(`api/get/schedules?from=${this.format(from)}&to=${this.format(to)}`);
      this.date = from;
      this.loading = false;
},
```

**Comment by jervalles** [comment]
thank you! I think I will go with that approch! 

one last question, about responsivity, do you have any idea ? on mobile the table is too just. When we got 5 days showed (or most dramatic, 7 days). I guess Doctolib showing only 4 days to solve this)

Great component you made there, thanks!

**Comment by iNeoO** [comment]
yes the best way is to change the number of element to display. You can add an event listener for this with a resize. You can use slots to reduce size of calendar too (reduce paddings, fonts, ...)

**Comment by jervalles** [comment]
Thank you everything work great! 

one more question before close this. How can I add a div saying that "there is is no meeting in this week" if there is no meeting in the actual showing week? 

I don't know if we can create custom templates

**Comment by iNeoO** [comment]
with the component, it's not possible, but u can set a div with position absolute over the meeting selector to say it.

**Comment by jervalles** [comment]
Alright that what I thought. Thank you very much for your feature. It's a great one.

Have a great day!
