### ISSUE TITLE
Allow override of empty templates

### ISSUE THREAD

**Issue by CSalih** [iNeoO/vue-meeting-selector#17]
Hello iNeoO,

i want to remove the `button-previous` and `button-next` button from the ui, but with the current approach (slot with `if`) it does not work.  

For example:
```
  <vue-meeting-selector :date="currentDate" :meetings-days="meetingsDays">
    <template #button-previous/>
    <template #button-next />
  </vue-meeting-selector>
```
Current Output: 
```
<div class="tab__pagination" :class="cssClass.tabPaginationNext">
    <button type="button" class="tab__pagination__button tab__pagination__button--right" :disabled="loading"
        :class="cssClass.tabPaginationNextButton" @click="nextDate">
        <arrow-icon direction="right" />
    </button>
</div>
```

Expected Output: 
```
<div class="tab__pagination" :class="cssClass.tabPaginationNext">
</div>
```

Putting the `button` into the `slot` tag would solve this problem, but i did not check if something else would get broken. What is the reason to use `<slot if.../> <button v-else />` instead of `<slot> <button/> </slot>`?

**Comment by iNeoO** [comment]
HI empty slot aren't detected by vuejs, maybe set an empty span inside ?
```
  <vue-meeting-selector :date="currentDate" :meetings-days="meetingsDays">
      <template #button-previous><span></span></template>
      <template #button-next><span></span></template>
  </vue-meeting-selector>
  ```
  for slot if, I did not know at the time I created the component that we could do this way, I will make a mr
