### ISSUE TITLE
How to add in nuxt?

### ISSUE THREAD

**Issue by lillodipiazza** [iNeoO/vue-meeting-selector#21]
Help me 🙂

**Comment by iNeoO** [comment]
Hi i tried with this version https://codesandbox.io/s/suspicious-haze-lcgiil

**Comment by lillodipiazza** [comment]
thankyou

i use 2.15.8

i copied your example but 500 - Cannot read properties of undefined (reading 'tabClass')

**Comment by lillodipiazza** [comment]
Nothing? :(

**Comment by webotop** [comment]
Hi guys, I am trying trying to get this works too, I added it on Nuxtjs via plugins but I get console errors regarding reactive property. 

For instance
[Vue warn]: Property or method "date" is not defined on the instance but referenced during render.
[Vue warn]: Property or method "loading" is not defined on the instance but referenced during render.
[Vue warn]: Property or method "classNames" is not defined on the instance but referenced during render.

and so on ...

I just followed the simple example on https://vue-meeting-selector.tuturu.io/#simpleexample

Any help would be appreciated.

Thanx

**Comment by iNeoO** [comment]
Hi can u provide some code ? did you define date, loading, classnames ? how did u geneeratee meetingsDays  >

**Comment by webotop** [comment]
> thankyou
> 
> i use 2.15.8
> 
> i copied your example but 500 - Cannot read properties of undefined (reading 'tabClass')

You need 2.6.x version of Nuxtjs

**Comment by webotop** [comment]
> Hi can u provide some code ? did you define date, loading, classnames ? how did u geneeratee meetingsDays ?

I re opened the issue. I guess i dunno where to define those properties. I just used the code from the simple example. 
Isn't date defined by new Date(), in js ?

**Comment by iNeoO** [comment]
these properies must be defined in the component using this components. It's some props

**Comment by webotop** [comment]
> these properties must be defined in the component using this components. It's some props

Well this is where I am struggling. I am using

`<template>
  <div class="simple-example container text-center">
    <vue-meeting-selector
      class="simple-example__meeting-selector"
      v-model="meeting"
      :date="date"
      :loading="loading"
      :class-names="classNames"
      :meetings-days="meetingsDays"
      @next-date="nextDate"
      @previous-date="previousDate"
    />
    <p>meeting Selected: {{ meeting ? meeting : 'No Meeting selected' }}</p>
  </div>
</template>`


I can't find any examples with filled properties.

**Comment by iNeoO** [comment]
most of them are in the doc only the generation of `meetingsDays` is missing 

`meetingsDays` is supposed to be generated by an api call anyway i wrote a script to generate them in TS (to create exemple) in the last version (using vue3 the file is available in JS) if you don t have api, you can use this file to generate slots.

`meeting`: is an array or null (date) depends if you set possible to select multiple slots
`date`: is the the first date of meetings slots available
`loading`: is to display a loading screen (boolean)
`ClassNames`: Is to set some custom class to the meeting-selector, it s optional
`nextDate/previousDate`: Is function used to update meetingsDays (make api call or generate again slots)

**Comment by webotop** [comment]
> most of them are in the doc only the generation of `meetingsDays` is missing
> 
> `meetingsDays` is supposed to be generated by an api call anyway i wrote a script to generate them in TS (to create exemple) in the last version (using vue3 the file is available in JS) if you don t have api, you can use this file to generate slots.
> 
> `meeting`: is an array or null (date) depends if you set possible to select multiple slots `date`: is the the first date of meetings slots available `loading`: is to display a loading screen (boolean) `ClassNames`: Is to set some custom class to the meeting-selector, it s optional `nextDate/previousDate`: Is function used to update meetingsDays (make api call or generate again slots)

Ok thanx for your kind explanations. So I am missing the api or the script, the tabs are not generated because of the empty meetingsDays. Where can I find the Api or js file ?

Also what is the date format I should use ?

**Comment by iNeoO** [comment]
It's your own api, for the script, he isn't available for the vue2 version, but you can copy it https://github.com/iNeoO/vue-meeting-selector/blob/feature/vue3/src/helpers/slotsGenerator.js

**Comment by jUll3n** [comment]
ah ok shd I import the file this way import "vue-meeting-selector/src/helpers/slotsGenerator.js"; in my js file under import VueMeetingSelector from 'vue-meeting-selector'; ?

**Comment by iNeoO** [comment]
you can't import it because he isn't available in js in vue-meeting-selector@1.1.1 You can copy it for the moment. (I will try to make a release today to add it)

there is an exemple here https://github.com/iNeoO/vue-meeting-selector/blob/master/src/components/Examples/SimpleExample.vue usung it

**Comment by jUll3n** [comment]
well I got this file cos I did an npm install my nuxtjs app. I checked its the same file as your link.

So do you mean it cannot works in nuxtjs ?

**Comment by iNeoO** [comment]
I altered the example to use the slotGenerator.js file https://codesandbox.io/s/suspicious-haze-lcgiil?file=/pages/index.vue

i published a new release 1.1.2 so you can directly import the file ``import slotsGenerator from "vue-meeting-selector/helpers/slotsGenerator";

File wasn't available on 1.1.2 (maybe you are using 2.0.0-beta-2, it s a a vue3 component)

**Comment by jUll3n** [comment]
Thanx for this again. Unfortunately When I am adding it in nuxtjs on a fresh install I am now getting the following error : 

Cannot read properties of undefined (reading 'tabClass');

I guess I'll come back into it later when I got more knowledge of Nuxtjs. 

Thanx for helping., you rox.

**Comment by iNeoO** [comment]
remove tablClass props in the template

**Comment by carollodn** [comment]
Hello @iNeoO, am I wrong or the example you linked doesn't work?

thank you
