### ISSUE TITLE
Vue3 + Typescript support

### ISSUE THREAD

**Issue by homersimpsons** [iNeoO/vue-meeting-selector#26]
Hello I would be interested with a Vue3 support for this library.

I came across this issue after attempting this https://github.com/iNeoO/vue-meeting-selector/issues/14.

Also there is no `.d.ts` in exported `/dist/lib` which makes TypeScript complain with

> TS7016: Could not find a declaration file for module 'vue-meeting-selector'

**Comment by iNeoO** [comment]
Hi, did you try to use version 2.0.0-beta-2 ? all types are available in src/interfaces

**Comment by KaisNeffati** [comment]
![image](https://user-images.githubusercontent.com/13632225/167262507-5c2301bb-df23-43ae-8c1e-2ca111dfcd61.png)
I have problems with the lib

**Comment by KaisNeffati** [comment]
@iNeoO could help please ?

**Comment by iNeoO** [comment]
hi, i changed the paths, try with 2.0.0-beta-3
