### ISSUE TITLE
How to access meeting.value after meeting-slot-selected is fired?

### ISSUE THREAD

**Issue by adriangzz** [iNeoO/vue-meeting-selector#27]
Hello, im trying to access meeting.value after a slot is selected. 

Im using this

`@meeting-slot-selected="handler"`

and for handler I have this function:

```
const handler = () => {
  console.log(meeting.value);
};
```

Whenever I click on a slot I get `null` printed.

Thanks!

**Comment by iNeoO** [comment]
HI

slot is passed as params to handler

so
```
const handler = (meeting) => {
  console.log(meeting);
};
```

should work

**Comment by adriangzz** [comment]
Thank you!
