### ISSUE TITLE
slotsGenerator setting the date one day before

### ISSUE THREAD

**Issue by adriangzz** [iNeoO/vue-meeting-selector#28]
Using the basic example with 
`slotsGenerator(
    newDate,
    nbDaysToDisplay.value,
    start,
    end,
    30
  );`

Will generate this array 
`[
{ 
date: Date Sun May 15 2022 19:00:00 GMT-0500 (Central Daylight Time), 
slots:  [
{ 
date: Date Mon May 16 2022 15:00:00 GMT-0500 (Central Daylight Time) 
},
​​​...
] 
}
​},
...
]`

As you can see, the first object has a date of Sunday May 15 and the first slot has a date of Monday May 16.
This is causing the days to be one off when selecting them as you can see in the next picture:

![Screenshot_2022-05-16_14-47-31](https://user-images.githubusercontent.com/29560208/168670642-f809208b-f3ee-4a79-8abe-21689a312697.png)

It should be 05/17/2022 09:30:00.

This issue also happens on the official [example](https://vue-meeting-selector.tuturu.io/#simpleexample).

**Comment by iNeoO** [comment]
I thx for your feedback, I think it's a TZ pb, since you are gmt -5

Wish params did you provide to the function ?

**Comment by adriangzz** [comment]
To `slotsGenerator( new Date(), 5, start, end, 30 );`

and start and end are equal to:

```
const start = {
    hours: 8,
    minutes: 0,
  };
  const end = {
    hours: 16,
    minutes: 0,
  };
```

**Comment by iNeoO** [comment]
HI, i was using a tz wrongly, i changed things, can you try with 2.0.0-beta-3 ? (doc is not updated since i migrate to v3 i need to find some time to migrate it)

**Comment by adriangzz** [comment]
Hello, now slotsGenerator is outputing the same day.

![Screenshot_2022-05-23_13-02-01](https://user-images.githubusercontent.com/29560208/169879943-0babb77b-39b5-45b3-a999-094470c81f48.png)

![Screenshot_2022-05-23_13-03-20](https://user-images.githubusercontent.com/29560208/169880210-d53760d4-ab8f-47dd-8f1a-8c9aa383e8ca.png)

The slots are still being generated correctly.

**Comment by amouratoglou** [comment]
try using moment.js "JavaScript's Date object tracks time in UTC internally, but typically accepts input and produces output in the local time of the computer it's running on."
moment.js will show you the right timezone where you are and also add a lot of tools I love and thank for everytime a date is in my screen.

**Comment by iNeoO** [comment]
Things habe been update since the moment, with big refacto update to v3 with doc
