### ISSUE TITLE
how to overide labels for monthLabel and dayLabel

### ISSUE THREAD

**Issue by amouratoglou** [iNeoO/vue-meeting-selector#31]
hi it might be a silly question but i'm struggling to overide default labels, how should I implement this settings change?
I've attempted to pass it as a prop, in the data, an attribute parameter, but nothing seems to pick up. thanks for the help.

**Comment by amouratoglou** [comment]
I just found how. by passing the settings object to calendar-options="calendarOptions"
```
  <vue-meeting-selector
      class="bookeame-calendar__meeting-selector"
      v-model="meeting"
      :date="date"
      :loading="loading"
      :class-names="classNames"
      **:calendar-options="calendarOptions"**
      :meetings-days="meetingsDays"
      @next-date="nextDate"
      @previous-date="previousDate"
    />
```
great work btw.

**Comment by iNeoO** [comment]
thx !
