### ISSUE TITLE
Missing imports with fresh install

### ISSUE THREAD

**Issue by Julien-degardin** [iNeoO/vue-meeting-selector#38]
Hi ! 

First, I want to thank you for coding such a package. It looks great!
However, I couldn't get it to work for the moment. 
I'm running a Vue 3 project in which I want to add a timeslot reservation system.
I followed the instructions given on your website (npm install + import), and tried to implement your example (https://vue-meeting-selector.tuturu.io/#simpleexample). But when I refresh, I get 
![image](https://user-images.githubusercontent.com/50171776/212708812-ace42ae4-e0a2-4501-9914-2405baa52020.png)

Did I do something wrong? 

Thanks a lot!

**Comment by iNeoO** [comment]
Hi, i missed some files into the publish with npm, it s should be fixed with 3.0.2

https://codesandbox.io/s/vue3-meeting-selector-hiloic?file=/src/App.vue

I made a simple exemple with codesandbox

**Comment by Julien-degardin** [comment]
Hello !
Thank you very much for this quick reply :)
I uninstalled and reinstalled your package in its latest version (3.0.2) but I'm now getting this error : 
![image](https://user-images.githubusercontent.com/50171776/212856998-92bfc638-14ac-4d16-9e4a-2e627736e738.png)

I noticed your demo on codesandbox is working so do you have any idea what could be causing it?

Thanks!

**Comment by iNeoO** [comment]
can you check the node_modules package to see if files are present ?

**Comment by Julien-degardin** [comment]
It seems they are there, here is my tree : 
![image](https://user-images.githubusercontent.com/50171776/212858763-43149781-676d-4e21-81a9-2a6b427fa741.png)

**Comment by iNeoO** [comment]
well i don't know, i had some probleme with cache on the codesandbox, but nothing more. Do you really need a lib to generate meeting slots ? If you have an api to generate availables slot use it instead of `slotsGenerator` other way you can copy the file.

**Comment by Julien-degardin** [comment]
I made it work ! 
I copied the file slotsGenerator.js and pasted it in my components folder and then imported it with 
`import SlotsGenerator from "@/components/slotsGenerator/slotsGenerator";`

![image](https://user-images.githubusercontent.com/50171776/212861382-e955a9e9-8f68-41a8-85ce-971d17d0c6f0.png)
Thank you for your advices !
