### ISSUE TITLE
Nuxt3 css is not loaded

### ISSUE THREAD

**Issue by urko-b** [iNeoO/vue-meeting-selector#39]
Hi, I've been following documentation [example](https://vue-meeting-selector.tuturu.io/#simplemultiexample) and I found some trouble while installing component, I'm able now to make it build but looks like css is not loaded. Could you please give me any clue how can I finally use this component. 

I have no error on console neither network when I inspect browser tab with F12.

This is my component
```vue
<template>
    <div class="simple-multi-example">
      <vue-meeting-selector
        class="simple-multi-example__meeting-selector"
        v-model="meeting"
        :date="date"
        :loading="loading"
        :class-names="classNames"
        :meetings-days="meetingsDays"
        :multi="true"
        @next-date="nextDate"
        @previous-date="previousDate"
      />
      <p>meeting Selected: {{ meeting.length ? meeting : 'No Meeting selected' }}</p>
    </div>
  </template>
  
  <script lang="ts">
  import {
    defineComponent,
    onMounted,
    ref,
    computed,
  } from 'vue';
  
  import VueMeetingSelector from 'vue-meeting-selector';
  // Function used to generate slots, use your own function
  import slotsGenerator from '@/helpers/slotsGenerator';
  
  import type MeetingsDay from 'vue-meeting-selector/src/interfaces/MeetingsDay.interface';
  import type MeetingSlot from 'vue-meeting-selector/src/interfaces/MeetingSlot.interface';
  import type Time from 'vue-meeting-selector/src/interfaces/Time.interface';
  
  export default defineComponent({
    name: 'SimpleMultiExample',
    components: {
      VueMeetingSelector,
    },
    setup() {
      const date = ref(new Date());
      const meetingsDays = ref<MeetingsDay[]>([]);
      const meeting = ref<MeetingSlot[]>([]);
      const loading = ref(true);
  
      const nbDaysToDisplay = computed(() => 5);
  
      // because of line-height, font-type you might need to change top value
      const classNames = computed(() => ({
        tabLoading: 'loading-div',
      }));
  
      // juste set async the gettings of meeting to display loading
      const slotsGeneratorAsync = (
        d: Date, // date
        n: number, // nbDaysToDisplay
        start: Time,
        end: Time,
        timesBetween: number,
      ):Promise<MeetingsDay[]> => new Promise((resolve) => {
        setTimeout(() => {
          resolve(slotsGenerator(d, n, start, end, timesBetween));
        }, 1000);
      });
  
      const nextDate = async () => {
        loading.value = true;
        const start: Time = {
          hours: 8,
          minutes: 0,
        };
        const end: Time = {
          hours: 16,
          minutes: 0,
        };
        const dateCopy = new Date(date.value);
        const newDate = new Date(dateCopy.setDate(dateCopy.getDate() + 7));
        date.value = newDate;
        meetingsDays.value = await slotsGeneratorAsync(
          newDate,
          nbDaysToDisplay.value,
          start,
          end,
          30,
        );
        loading.value = false;
      };
  
      const previousDate = async () => {
        loading.value = true;
        const start: Time = {
          hours: 8,
          minutes: 0,
        };
        const end: Time = {
          hours: 16,
          minutes: 0,
        };
        const dateCopy = new Date(date.value);
        dateCopy.setDate(dateCopy.getDate() - 7);
        const formatingDate = (dateToFormat: Date): String => {
          const d = new Date(dateToFormat);
          const day = d.getDate() < 10 ? `0${d.getDate()}` : d.getDate();
          const month = d.getMonth() + 1 < 10 ? `0${d.getMonth() + 1}` : d.getMonth() + 1;
          const year = d.getFullYear();
          return `${year}-${month}-${day}`;
        };
        const newDate = formatingDate(new Date()) >= formatingDate(dateCopy)
          ? new Date()
          : new Date(dateCopy);
        date.value = newDate;
        meetingsDays.value = await slotsGeneratorAsync(
          newDate,
          nbDaysToDisplay.value,
          start,
          end,
          30,
        );
        loading.value = false;
      };
  
      onMounted(async () => {
        const start: Time = {
          hours: 8,
          minutes: 0,
        };
        const end: Time = {
          hours: 16,
          minutes: 0,
        };
        meetingsDays.value = await slotsGeneratorAsync(
          date.value,
          nbDaysToDisplay.value,
          start,
          end,
          30,
        );
        loading.value = false;
      });
  
      return {
        date,
        meetingsDays,
        meeting,
        loading,
        nbDaysToDisplay,
        classNames,
        nextDate,
        previousDate,
      };
    },
  });
  </script>
  
  <style scoped lang="scss">
  .simple-multi-example {
    &__meeting-selector {
      max-width: 542px;
    }
  }
  // since our scss is scoped we need to use ::v-deep
  :deep(.loading-div) {
    top: 58px!important;
  }
  </style>
```

This my nuxt configuration
```typescript
export default defineNuxtConfig({
    ssr: false,
    app: {
        head: {
            title: "test",
        },
    },
	css: [ "~/assets/css/main.css"],
	postcss: {
		plugins: {
			tailwindcss: {},
			autoprefixer: {},
		},
	},
    devServer: {
        port: 12345,
    },
    modules: [],
    build: {
    }
})

```
![image](https://user-images.githubusercontent.com/11888892/228344972-b5f3a26f-5db2-44c0-bf89-f2eb140f29f3.png)

**Comment by urko-b** [comment]
ok I've added this line and looks like css now is working: `  import 'vue-meeting-selector/dist/style.css';`
It would be great if both could work together to fix this problem. I'm around if you need feedback from my side
![image](https://user-images.githubusercontent.com/11888892/228347194-9c68dd2f-615f-4f1f-9491-7ed8e7cd4b32.png)

**Comment by iNeoO** [comment]
HI, i will update the doc

**Comment by fallingsky2023** [comment]
I am using nuxt3 too and I am trying to make a component build, but it didn't succeed for now.
I get the error: Missing "./src/helpers/slotsGenerator" specifier in "vue-meeting-selector" package.

Here is my package.json file:
`
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^6.6.7",
    "@types/node": "^18",
    "nuxt": "^3.4.3",
    "vue": "^3.2.36"
  },
  "dependencies": {
    "axios": "^1.4.0",
    "sass": "^1.62.1",
    "vue-meeting-selector": "^3.0.2"
  }
}

`
Here is my nuxt.config.js file:
`
export default ({
    modules: [
      '@nuxtjs/tailwindcss',
    ],
})

`


Here is my component from the Simple example [here ](https://vue-meeting-selector.tuturu.io/#simpleexample):
`<template>
  <div class="simple-example">
    <vue-meeting-selector
      class="simple-example__meeting-selector"
      v-model="meeting"
      :date="date"
      :loading="loading"
      :class-names="classNames"
      :meetings-days="meetingsDays"
      @next-date="nextDate"
      @previous-date="previousDate"
    />
    <p>meeting Selected: {{ meeting ? meeting : 'No Meeting selected' }}</p>
  </div>
</template>

<script lang="ts">
import {
  defineComponent,
  onMounted,
  ref,
  computed,
} from 'vue';

import VueMeetingSelector from 'vue-meeting-selector';
// Function used to generate slots, use your own function
import slotsGenerator from 'vue-meeting-selector/src/helpers/slotsGenerator';

import type MeetingsDay from 'vue-meeting-selector/src/interfaces/MeetingsDay.interface';
import type MeetingSlot from 'vue-meeting-selector/src/interfaces/MeetingSlot.interface';
import type Time from 'vue-meeting-selector/src/interfaces/Time.interface';

export default defineComponent({
  name: 'SimpleExample',
  components: {
    VueMeetingSelector,
  },
  setup() {
    const date = ref(new Date());
    const meetingsDays = ref<MeetingsDay[]>([]);
    const meeting = ref<MeetingSlot | null>(null);
    const loading = ref(true);

    const nbDaysToDisplay = computed(() => 5);

    // because of line-height, font-type you might need to change top value
    const classNames = computed(() => ({
      tabLoading: 'loading-div',
    }));

    // juste set async the gettings of meeting to display loading
    const slotsGeneratorAsync = (
      d: Date, // date
      n: number, // nbDaysToDisplay
      start: Time,
      end: Time,
      timesBetween: number,
    ):Promise<MeetingsDay[]> => new Promise((resolve) => {
      setTimeout(() => {
        resolve(slotsGenerator(d, n, start, end, timesBetween));
      }, 1000);
    });

    const nextDate = async () => {
      loading.value = true;
      const start: Time = {
        hours: 8,
        minutes: 0,
      };
      const end: Time = {
        hours: 16,
        minutes: 0,
      };
      const dateCopy = new Date(date.value);
      const newDate = new Date(dateCopy.setDate(dateCopy.getDate() + 7));
      date.value = newDate;
      meetingsDays.value = await slotsGeneratorAsync(
        newDate,
        nbDaysToDisplay.value,
        start,
        end,
        30,
      );
      loading.value = false;
    };

    const previousDate = async () => {
      loading.value = true;
      const start: Time = {
        hours: 8,
        minutes: 0,
      };
      const end: Time = {
        hours: 16,
        minutes: 0,
      };
      const dateCopy = new Date(date.value);
      dateCopy.setDate(dateCopy.getDate() - 7);
      const formatingDate = (dateToFormat: Date): String => {
        const d = new Date(dateToFormat);
        const day = d.getDate() < 10 ? `0${d.getDate()}` : d.getDate();
        const month = d.getMonth() + 1 < 10 ? `0${d.getMonth() + 1}` : d.getMonth() + 1;
        const year = d.getFullYear();
        return `${year}-${month}-${day}`;
      };
      const newDate = formatingDate(new Date()) >= formatingDate(dateCopy)
        ? new Date()
        : new Date(dateCopy);
      date.value = newDate;
      meetingsDays.value = await slotsGeneratorAsync(
        newDate,
        nbDaysToDisplay.value,
        start,
        end,
        30,
      );
      loading.value = false;
    };

    onMounted(async () => {
      const start: Time = {
        hours: 8,
        minutes: 0,
      };
      const end: Time = {
        hours: 16,
        minutes: 0,
      };
      meetingsDays.value = await slotsGeneratorAsync(
        date.value,
        nbDaysToDisplay.value,
        start,
        end,
        30,
      );
      loading.value = false;
    });

    return {
      date,
      meetingsDays,
      loading,
      nbDaysToDisplay,
      classNames,
      nextDate,
      previousDate,
    };
  },
});
</script>

<style scoped lang="scss">
.simple-example {
  &__meeting-selector {
    max-width: 542px;
  }
}
// since our scss is scoped we need to use ::v-deep
:deep(.loading-div) {
  top: 58px!important;
}
</style>`

Here is my page code:
`<template>
<div>
    <Calendar />
</div>
</template>

`

**Comment by iNeoO** [comment]
fallingsky2023 Can you create this issue i m closing this one (doc has been updated)
