### ISSUE TITLE
If timesBetween argument to slotsGeneratorAsync is 0 causes browser to crash

### ISSUE THREAD

**Issue by abbjetmus** [iNeoO/vue-meeting-selector#42]
If timesBetween argument to slotsGeneratorAsync is 0 then it causes browser to crash. Had it zero by mistake before realizing this. Not sure about the reason haven't digged in the source code.

**Comment by iNeoO** [comment]
Hi, I will add a protection

**Comment by iNeoO** [comment]
I added an error in 3.0.3
