### ISSUE TITLE
Select or unselect a meeting by method call

### ISSUE THREAD

**Issue by dlik** [iNeoO/vue-meeting-selector#44]
Hiya!

Is there any way to select or unselect an event by hand (i.e. by a method call)?
I want to allow the user to select a maximum of two events. Thus, it would be great if there was a way to unselect the event that was just selected. I didn't find a way to do that in the documentation. Am I missing anything?

Thank you so much and kind regards

**Comment by iNeoO** [comment]
Hi,

You can use @change event

```html
    <vue-meeting-selector
      ref="meetingSelector"
      class="meeting-selector"
      multi
      v-model="meeting"
      :date="date"
      :loading="false"
      :meetings-days="meetingsDays"
      @next-date="nextDate"
      @previous-date="previousDate"
      @change="change">
```


```javascript
const change = (value: MeetingSlot[]) => {
      if (value.length > 2) {
        value.shift();
      }
    };
```
