### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Abdus-Salam** [iNeoO/vue-meeting-selector#6]
I have followed the full process. But in browser shows TypeError: Cannot read property 'length' of undefined. Please help me.

**Comment by iNeoO** [comment]
can you show your code ? or  an exemple ?

**Comment by Abdus-Salam** [comment]
<template>
  <vue-meeting-selector
    v-model="meeting"
    :date="date"
    :loading="loading"
    :meetings-days="meetingsDays"
    @next-date="nextDate"
    @previous-date="previousDate"
  />
</template>
 
<script>
import VueMeetingSelector from "vue-meeting-selector";

export default {
  components: {
    VueMeetingSelector
  },
  data() {
    return {
      date: new Date(),
      meeting: null,
      loading: false,
      meetingsDays: []
    };
  },
  methods: {
    getMeetings(date) {
      // methods who return the meetings
    },
    async nextDate() {
      this.loading = true;
      const date = new Date(this.date);
      date.setDate(date.getDate() + 7);
      this.meetingsDays = await this.getMeetings(date);
      this.date = date;
      this.loading = false;
    },
    async previousDate() {
      this.loading = true;
      const date = new Date(this.date);
      date.setDate(date.getDate() - 7);
      this.meetingsDays = await this.getMeetings(date);
      this.date = date;
      this.loading = false;
    }
  },
  async created() {
    this.loading = true;
    this.meetingsDays = await this.getMeetings(this.date);
    this.loading = false;
  }
};
</script>

**Comment by iNeoO** [comment]
Ok this is just an exemple, you need to complete getMeetings(date) with a function who will generate/get from your backend meetingsSlots 
```
interface MeetingSlot {
  date: Date | string;
  [key: string]: any;
}
```
