### ISSUE TITLE
Are you planning to add select multiple time functionality? 

### ISSUE THREAD

**Issue by demiremredev** [iNeoO/vue-meeting-selector#9]
Are you planning to add select multiple time functionality?

**Comment by iNeoO** [comment]
Hi if you need it, i can try to implement it.

**Comment by demiremredev** [comment]
It can be very useful. Maybe you can add a prop like this: multiSelectMode: {type: Boolean, default: false}. If it is true our model can be array of objects like this: [{date:xxx}, {date:xxx}, {date:xxx}]. And i believe that it can raise the popularity of npm module. Thanks.

**Comment by iNeoO** [comment]
Yeah i will do that asap !
